from flask_wtf import FlaskForm
from wtforms import StringField


class ProgramForm(FlaskForm):
    wvi_11 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_11 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_11 = StringField(render_kw={"placeholder": "Fist"})
    fsd_11 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_11 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_11 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_12 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_12 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_12 = StringField(render_kw={"placeholder": "Fist"})
    fsd_12 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_12 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_12 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_13 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_13 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_13 = StringField(render_kw={"placeholder": "Fist"})
    fsd_13 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_13 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_13 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_14 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_14 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_14 = StringField(render_kw={"placeholder": "Fist"})
    fsd_14 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_14 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_14 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_15 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_15 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_15 = StringField(render_kw={"placeholder": "Fist"})
    fsd_15 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_15 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_15 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_16 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_16 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_16 = StringField(render_kw={"placeholder": "Fist"})
    fsd_16 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_16 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_16 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_17 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_17 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_17 = StringField(render_kw={"placeholder": "Fist"})
    fsd_17 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_17 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_17 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_21 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_21 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_21 = StringField(render_kw={"placeholder": "Fist"})
    fsd_21 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_21 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_21 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_22 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_22 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_22 = StringField(render_kw={"placeholder": "Fist"})
    fsd_22 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_22 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_22 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_23 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_23 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_23 = StringField(render_kw={"placeholder": "Fist"})
    fsd_23 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_23 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_23 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_24 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_24 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_24 = StringField(render_kw={"placeholder": "Fist"})
    fsd_24 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_24 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_24 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_25 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_25 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_25 = StringField(render_kw={"placeholder": "Fist"})
    fsd_25 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_25 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_25 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_26 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_26 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_26 = StringField(render_kw={"placeholder": "Fist"})
    fsd_26 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_26 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_26 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_27 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_27 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_27 = StringField(render_kw={"placeholder": "Fist"})
    fsd_27 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_27 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_27 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_31 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_31 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_31 = StringField(render_kw={"placeholder": "Fist"})
    fsd_31 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_31 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_31 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_32 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_32 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_32 = StringField(render_kw={"placeholder": "Fist"})
    fsd_32 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_32 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_32 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_33 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_33 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_33 = StringField(render_kw={"placeholder": "Fist"})
    fsd_33 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_33 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_33 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_34 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_34 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_34 = StringField(render_kw={"placeholder": "Fist"})
    fsd_34 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_34 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_34 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_35 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_35 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_35 = StringField(render_kw={"placeholder": "Fist"})
    fsd_35 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_35 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_35 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_36 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_36 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_36 = StringField(render_kw={"placeholder": "Fist"})
    fsd_36 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_36 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_36 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_37 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_37 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_37 = StringField(render_kw={"placeholder": "Fist"})
    fsd_37 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_37 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_37 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_41 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_41 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_41 = StringField(render_kw={"placeholder": "Fist"})
    fsd_41 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_41 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_41 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_42 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_42 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_42 = StringField(render_kw={"placeholder": "Fist"})
    fsd_42 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_42 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_42 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_43 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_43 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_43 = StringField(render_kw={"placeholder": "Fist"})
    fsd_43 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_43 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_43 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_44 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_44 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_44 = StringField(render_kw={"placeholder": "Fist"})
    fsd_44 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_44 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_44 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_45 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_45 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_45 = StringField(render_kw={"placeholder": "Fist"})
    fsd_45 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_45 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_45 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_46 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_46 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_46 = StringField(render_kw={"placeholder": "Fist"})
    fsd_46 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_46 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_46 = StringField(render_kw={"placeholder": "Rest Durations"})
    wvi_47 = StringField(render_kw={"placeholder": "Wave In"})
    wvo_47 = StringField(render_kw={"placeholder": "Wave Out"})
    fst_47 = StringField(render_kw={"placeholder": "Fist"})
    fsd_47 = StringField(render_kw={"placeholder": "Fingers Spread"})
    dtp_47 = StringField(render_kw={"placeholder": "Double Tap"})
    rst_47 = StringField(render_kw={"placeholder": "Rest Durations"})
